# -*- coding: UTF-8 -*-

# 字典
BATCH_PAD = 'BATCH_PAD'
BATCH_PAD_VAL = 0
UNK = 'UNK'
UNK_VAL = 1
STRT = 'STRT'
STRT_VAL = 2
END = 'END'
END_VAL = 3

# 标注标签
TAG_PAD = 'P'
TAG_BEGIN = 'B'
TAG_INSIDE = 'I'
TAG_END = 'E'
TAG_SINGLE = 'S'
TAG_OTHER = 'O'

# 映射表
CWS_TAGS = (TAG_BEGIN, TAG_INSIDE, TAG_END, TAG_SINGLE,TAG_PAD)
NER_TAGS = (TAG_BEGIN,TAG_INSIDE,TAG_OTHER,TAG_PAD)
